// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU4ouKtf4KK9m8pE9kEItpaAxrXTxckwg',
    appId: '1:345909511283:web:3ed45c952035e2dd159606',
    messagingSenderId: '345909511283',
    projectId: 'crud-ops-4b48b',
    authDomain: 'crud-ops-4b48b.firebaseapp.com',
    storageBucket: 'crud-ops-4b48b.appspot.com',
    measurementId: 'G-LMY5WS925H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWu8PaXe0lrHpPDPFK_ijcZR8S_fclM0',
    appId: '1:345909511283:android:50561c141e77e315159606',
    messagingSenderId: '345909511283',
    projectId: 'crud-ops-4b48b',
    storageBucket: 'crud-ops-4b48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGvnfv-3ORC5svU6oK-ftYgRksPPOQko',
    appId: '1:345909511283:ios:0ad7922e4c8b2376159606',
    messagingSenderId: '345909511283',
    projectId: 'crud-ops-4b48b',
    storageBucket: 'crud-ops-4b48b.appspot.com',
    iosClientId: '345909511283-4le8lnbf2503jqjms866qohb2usjol79.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGvnfv-3ORC5svU6oK-ftYgRksPPOQko',
    appId: '1:345909511283:ios:0ad7922e4c8b2376159606',
    messagingSenderId: '345909511283',
    projectId: 'crud-ops-4b48b',
    storageBucket: 'crud-ops-4b48b.appspot.com',
    iosClientId: '345909511283-4le8lnbf2503jqjms866qohb2usjol79.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );
}
